---
- name: Removing OpenVPN server
  tags:
    - remove_fs_monitoring
    - remove_fs
    - ubuntu_22_04
  block:
    - name: Removing monitoring on FS side
      debug:
        msg: "Removing Monitoring from {{ inventory_hostname }}"
    
    - name: Stop and disable the iperf service
      systemd:
        name: "{{ item }}"
        state: stopped
        enabled: false
      loop:
        - "ovpn-iperf3"
      ignore_errors: true
      notify: Reload systemd
    
    - name: Remove systemd service files
      file:
        path: "/etc/systemd/system/{{ item }}"
        state: absent
      loop:
        - "ovpn-iperf3.service"
      notify:  Reload systemd
