
# Default variables for Ubuntu systems
---

#### Packages
required_packages:
  - iperf3

iperf_bind_address : "10.200.0.2"
iperf_server_address : "10.200.0.1"
iperf_server_port : 5005
iperf_path : "/usr/bin/iperf3"
iperf_run_period : 30 # run iperf every x seconds
iperf_dl_speed_guage_metric_name : "TUNNEL_DL"
iperf_ul_speed_guage_metric_name : "TUNNEL_UL"


loadtime_peer_prometheus_metric_port : 8008
loadtime_prometheus_expose_port : 8008
loadtime_prometheus_listen_addr : "127.0.0.1"
loadtime_interval : 10

IR_FS_tunnel_interface : "tun0"

remove_monitoring: false

monit_dir :  "/opt/ovpn_monitoring"
python_path : "/usr/bin/python3"
prometheus_iperf_endpoint_port : 8001
prometheus_iperf_listen_addr : "127.0.0.1"

target_ssh_key : "keys/{{ inventory_hostname }}_ssh_key.pem"
ansible_ssh_private_key_file : "{{ target_ssh_key }}"

prometheus_listen_address : "0.0.0.0"
prometheus_listen_port : 9090
prometheus_version : "2.37.8"
prometheus_arch : "linux-amd64"
prometheus_download_url : "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.{{ prometheus_arch }}.tar.gz"

