---
- name: Adding a client to the serve
  debug:
    msg: "Adding a client to {{ inventory_hostname }}"

- name: Make sure the required direcotries exist
  file:
    path: "{{ client_root }}"
    state: directory

- name: Templating the addclient.sh script and config template to the server
  template:
    src: "opt/ovpn/clients/{{ item }}"
    dest: "{{ client_root }}/{{ item }}"
    mode: '0755'
  loop:
    - "addclient.sh"
    - "template.ovpn"

- name: Running the script and capturing output
  shell:
    cmd: "./addclient.sh {{ num_of_cli }}"
    chdir: "{{ client_root }}"
  register: script_output

- name: Set a list of client config files ans passwords
  set_fact:
    cli_conf_list: "{{ script_output.stdout_lines[1].split(',') }}"
    cli_pass_list: "{{ script_output.stdout_lines[0].split(',') }}"

- name: Fetching the client config files from the server
  fetch:
    src: "{{ item }}"
    dest: "{{ output_conf_dir }}/{{ item | basename }}"
    flat: yes
  loop: "{{ cli_conf_list }}"

- name: Removing the client config files from the server
  file:
    path: "{{ item }}"
    state: absent
  loop: "{{ cli_conf_list }}"

- name: Printing config file names and associated passwords
  debug:
    msg: "Config: {{ item | basename }}, Pass: {{ cli_pass_list[idx] }}" 
  loop: "{{ cli_conf_list }}"
  loop_control:
    index_var: idx
