---
- name: Templating the nofilter service and timer
  template:
    src: "{{ item }}"
    dest: "/{{ item }}"
  loop:
    - "etc/systemd/system/nofilter.service"
    - "etc/systemd/system/nofilter.timer"

- name: Reload systemd
  systemd:
    daemon-reload: yes

- name: Enabling nofilter service and timer
  systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - "nofilter.service"
    - "nofilter.timer"
